[package]
name = "rs-keyfile"
version = "0.1.0"
edition = "2024"

[lib]
name = "keyfile"
path = "src/lib.rs"

[[bin]]
name = "rs-keyfile"
path = "src/main.rs"

[dependencies]
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
